language: python

python:
    - 2.7
    - 3.5
    - 3.6
    - pypy
    - pypy3.5

matrix:
    include:
        - python: "3.7"
          dist: xenial

install:
    - pip install -U setuptools
    - pip install zc.buildout
    - pip install coveralls coverage
    - buildout bootstrap
    - buildout

script:
    - coverage run bin/test -v1

notifications:
    email: false

after_success:
    - coveralls

cache:
  pip: true
  directories:
    - eggs/
