language: python

dist: focal

python:
    - "2.7"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
    - pypy2
    - pypy3

install:
    - pip install -U setuptools
    - pip install zc.buildout
    - pip install coveralls coverage
    - buildout bootstrap
    - buildout

script:
    - coverage run bin/test -v1

notifications:
    email: false

after_success:
    - coveralls

cache:
  pip: true
  directories:
    - eggs/
